import { Catalog, ServiceCategory, StaffMember } from "@/lib/types";
import { getNextOpenDate } from "@/lib/utils";

const categories: ServiceCategory[] = [
  {
    id: "kuafor",
    name: "Kuafor",
    slug: "kuafor",
    description: "Kesim, fön ve renk dokunuşlarıyla görünümünü yenileyen saç tasarımları.",
    accent: "from-[#f4d6d7] to-[#f1e0d3]",
    heroLine: "Saçta zarif dönüşüm ritüelleri",
  },
  {
    id: "ayak-bakimi",
    name: "Ayak Bakımı",
    slug: "ayak-bakimi",
    description: "Spa pedikürden topuk yenilemeye kadar hafifletici bakım protokolleri.",
    accent: "from-[#f8efe5] to-[#d9e2d2]",
    heroLine: "Hafiflik hissiyle biten bakımlar",
  },
  {
    id: "tirnak-bakimi",
    name: "Tırnak Bakımı",
    slug: "tirnak-bakimi",
    description: "Manikür, kalıcı oje ve protez bakımında kusursuz detay odaklı uygulamalar.",
    accent: "from-[#f9dee4] to-[#f2ece7]",
    heroLine: "Temiz çizgiler, parlak bitişler",
  },
  {
    id: "epilasyon",
    name: "Epilasyon",
    slug: "epilasyon",
    description: "Konforlu, düzenli ve planlı seanslar için kişiye göre ayarlanan epilasyon seçenekleri.",
    accent: "from-[#ead7cd] to-[#efe6de]",
    heroLine: "Pürüzsüz his için kontrollü seanslar",
  },
  {
    id: "g5",
    name: "G5",
    slug: "g5",
    description: "Sıkılaşma ve toparlanma odağında kısa ama etkili seans programları.",
    accent: "from-[#e1e5d9] to-[#f6e8dd]",
    heroLine: "Ritmini bedenine geri veren protokoller",
  },
  {
    id: "cilt-bakimi",
    name: "Cilt Bakımı",
    slug: "cilt-bakimi",
    description: "Işıltı, nem dengesi ve bakım sonucu görünür dokunuşlar sunan seanslar.",
    accent: "from-[#f6e5e2] to-[#f8f1ea]",
    heroLine: "Ciltte sakin ve aydınlık görünüm",
  },
  {
    id: "masaj",
    name: "Masaj",
    slug: "masaj",
    description: "Dinlenme, gevşeme ve ritim düzenleme odaklı masaj deneyimleri.",
    accent: "from-[#dfe4d9] to-[#f3ebe3]",
    heroLine: "Bedeni yavaşlatan nazik seanslar",
  },
  {
    id: "kafa-masaji",
    name: "Kafa Masajı",
    slug: "kafa-masaji",
    description: "Kısa sürede rahatlama ve stres azaltma hissi veren uzman dokunuşlar.",
    accent: "from-[#ece4dd] to-[#f4dede]",
    heroLine: "Yoğun günler için kısa nefes alanları",
  },
  {
    id: "sac-taramasi",
    name: "Saç Taraması",
    slug: "sac-taramasi",
    description: "Saç ve saç derisi analiziyle destekleyici bakım planı oluşturan taramalar.",
    accent: "from-[#f7ebe1] to-[#e5ebdf]",
    heroLine: "Saç yolculuğunu veriye dayalı başlat",
  },
];

const staffSeeds: Record<string, Array<{ name: string; title: string; signature: string }>> = {
  kuafor: [
    { name: "Zeynep Arın", title: "Saç Tasarım Uzmanı", signature: "Doğal geçişli renkler", },
    { name: "Elif Tunca", title: "Styling Uzmanı", signature: "Fön ve parlak bitiş", },
    { name: "Derya Sayan", title: "Kesim Uzmanı", signature: "Yüz formuna uygun kesimler", },
  ],
  "ayak-bakimi": [
    { name: "Selin Uslu", title: "Spa Pedikür Uzmanı", signature: "Yumuşatıcı bakım protokolleri", },
    { name: "Aylin Ece", title: "Ayak Bakım Uzmanı", signature: "Konfor odaklı seans akışı", },
    { name: "Şule Deniz", title: "Bakım Terapisti", signature: "Topuk yenileme rutini", },
  ],
  "tirnak-bakimi": [
    { name: "Merve Aktaş", title: "Nail Artist", signature: "Minimal ve sofistike tasarımlar", },
    { name: "Gamze Ilıca", title: "Kalıcı Oje Uzmanı", signature: "Uzun süre dayanıklı uygulamalar", },
    { name: "Buse Koral", title: "Protez Tırnak Uzmanı", signature: "Temiz form ve bakım dengesi", },
  ],
  epilasyon: [
    { name: "Tuğçe Baş", title: "Lazer Epilasyon Uzmanı", signature: "Düzenli seans planlama", },
    { name: "Ceren Yalçın", title: "Cihaz Uygulama Uzmanı", signature: "Konforlu işlem temposu", },
    { name: "Sude Kılıç", title: "Seans Koordinatörü", signature: "Bölgesel takip ve planlama", },
  ],
  g5: [
    { name: "İlayda Özen", title: "G5 Uzmanı", signature: "Toparlayıcı seans serileri", },
    { name: "Pelin Uçar", title: "Body Sculpt Uzmanı", signature: "Ritimli uygulama yaklaşımı", },
    { name: "Ceyda Er", title: "Beden Bakım Uzmanı", signature: "Programlı sıkılaşma takibi", },
  ],
  "cilt-bakimi": [
    { name: "Nazlı Duran", title: "Cilt Terapisti", signature: "Nem ve ışıltı dengesi", },
    { name: "Ece Nur", title: "Hydrafacial Uzmanı", signature: "Arınma ve canlı görünüm", },
    { name: "Melis Kaan", title: "Bakım Danışmanı", signature: "Hassas cilt rutinleri", },
  ],
  masaj: [
    { name: "Burcu Işık", title: "Masaj Terapisti", signature: "Gevşeme odaklı seanslar", },
    { name: "Esra Yücel", title: "Aromaterapi Uzmanı", signature: "Ritüel hissi güçlü deneyim", },
    { name: "Sena Can", title: "Relaksasyon Terapisti", signature: "Boyun ve sırt rahatlatma", },
  ],
  "kafa-masaji": [
    { name: "Lina Toprak", title: "Kafa Masajı Uzmanı", signature: "Kısa sürede derin rahatlama", },
    { name: "Gizem Alkan", title: "Head Spa Terapisti", signature: "Sakinleştirici temas ritmi", },
    { name: "İrem Asil", title: "Wellness Uzmanı", signature: "Stres azaltan seans akışı", },
  ],
  "sac-taramasi": [
    { name: "Aslı Soner", title: "Saç Analiz Uzmanı", signature: "Saç derisi tarama ve yorumlama", },
    { name: "Nehir Karaca", title: "Saç Sağlığı Danışmanı", signature: "Dökülme analizi", },
    { name: "Begüm Aksu", title: "Saç Bakım Danışmanı", signature: "Takip planı oluşturma", },
  ],
};

const gradients = [
  "from-[#f6d8da] to-[#f6ece1]",
  "from-[#efe2d8] to-[#dfe5d8]",
  "from-[#f9e5eb] to-[#f4efe8]",
];

const staff: StaffMember[] = categories.flatMap((category) =>
  (staffSeeds[category.id] || []).map((entry, index) => ({
    id: `${category.id}-staff-${index + 1}`,
    name: entry.name,
    title: entry.title,
    categoryId: category.id,
    bio: `${category.name} alanında sakin, özenli ve planlı bir deneyim tasarlayan uzman ekip üyesi.`,
    specialties: [entry.signature, category.heroLine, "Kişiye özel bakım önerileri"],
    signature: entry.signature,
    gradient: gradients[index % gradients.length],
    workingDays: [1, 2, 3, 4, 5, 6],
    startHour: category.id === "masaj" ? 11 : 10,
    endHour: category.id === "kuafor" ? 20 : 19,
  })),
);

const categoryStaffIds = Object.fromEntries(
  categories.map((category) => [
    category.id,
    staff.filter((member) => member.categoryId === category.id).map((member) => member.id),
  ]),
) as Record<string, string[]>;

export const catalog: Catalog = {
  categories,
  staff,
  services: [
    {
      id: "signature-cut",
      categoryId: "kuafor",
      name: "Signature Kesim & Fön",
      description: "Yüz formuna göre kesim ve hacimli fön ile tamamlanan salon imzası.",
      durationMinutes: 75,
      price: 1500,
      featured: true,
      tag: "En çok tercih edilen",
      staffIds: categoryStaffIds.kuafor,
    },
    {
      id: "gloss-refresh",
      categoryId: "kuafor",
      name: "Işıltı Yenileme Bakımı",
      description: "Saça parlaklık ve yumuşaklık kazandıran bakım odaklı seans.",
      durationMinutes: 60,
      price: 1250,
      staffIds: categoryStaffIds.kuafor,
    },
    {
      id: "spa-pedicure",
      categoryId: "ayak-bakimi",
      name: "Spa Pedikür",
      description: "Temizlik, şekillendirme ve yumuşatıcı spa dokunuşları.",
      durationMinutes: 60,
      price: 1200,
      featured: true,
      staffIds: categoryStaffIds["ayak-bakimi"],
    },
    {
      id: "heel-renewal",
      categoryId: "ayak-bakimi",
      name: "Topuk Yenileme Ritüeli",
      description: "Kuruluk görünümünü azaltan derin bakım adımları.",
      durationMinutes: 45,
      price: 950,
      staffIds: categoryStaffIds["ayak-bakimi"],
    },
    {
      id: "manicure-gel",
      categoryId: "tirnak-bakimi",
      name: "Manikür + Kalıcı Oje",
      description: "Temiz manikür ve parlak uzun ömürlü kalıcı oje uygulaması.",
      durationMinutes: 75,
      price: 1450,
      featured: true,
      staffIds: categoryStaffIds["tirnak-bakimi"],
    },
    {
      id: "nail-strength",
      categoryId: "tirnak-bakimi",
      name: "Tırnak Güçlendirme Bakımı",
      description: "İnce tırnaklar için destekleyici, koruyucu uygulama adımı.",
      durationMinutes: 45,
      price: 900,
      staffIds: categoryStaffIds["tirnak-bakimi"],
    },
    {
      id: "targeted-epilation",
      categoryId: "epilasyon",
      name: "Bölgesel Epilasyon",
      description: "Kişisel plana uygun bölgesel seans düzenlemesi.",
      durationMinutes: 45,
      price: 950,
      featured: true,
      staffIds: categoryStaffIds.epilasyon,
    },
    {
      id: "full-body-epilation",
      categoryId: "epilasyon",
      name: "Tüm Vücut Epilasyon",
      description: "Daha geniş alanlar için planlı ve takipli uygulama paketi.",
      durationMinutes: 90,
      price: 2100,
      staffIds: categoryStaffIds.epilasyon,
    },
    {
      id: "g5-tightening",
      categoryId: "g5",
      name: "G5 Sıkılaştırma Seansı",
      description: "Kısa sürede ritimli, toparlayıcı bakım deneyimi.",
      durationMinutes: 45,
      price: 1100,
      featured: true,
      staffIds: categoryStaffIds.g5,
    },
    {
      id: "g5-lymph",
      categoryId: "g5",
      name: "G5 Destek Seansı",
      description: "Programlı uygulama takviminin destekleyici seans adımı.",
      durationMinutes: 60,
      price: 1350,
      staffIds: categoryStaffIds.g5,
    },
    {
      id: "hydra-glow",
      categoryId: "cilt-bakimi",
      name: "Hydra Glow Cilt Bakımı",
      description: "Arınma, nem ve ışıldayan görünüm etkisini hedefleyen bakım.",
      durationMinutes: 60,
      price: 1700,
      featured: true,
      tag: "Premium bakım",
      staffIds: categoryStaffIds["cilt-bakimi"],
    },
    {
      id: "collagen-reset",
      categoryId: "cilt-bakimi",
      name: "Kolajen Reset Protokolü",
      description: "Daha tok ve canlı bir görünüm için destekleyici bakım adımları.",
      durationMinutes: 75,
      price: 1950,
      staffIds: categoryStaffIds["cilt-bakimi"],
    },
    {
      id: "aroma-massage",
      categoryId: "masaj",
      name: "Aromaterapi Masajı",
      description: "Derin gevşeme için yavaş ritimli, esans destekli masaj.",
      durationMinutes: 60,
      price: 1800,
      featured: true,
      staffIds: categoryStaffIds.masaj,
    },
    {
      id: "back-neck-release",
      categoryId: "masaj",
      name: "Sırt & Boyun Rahatlatma",
      description: "Masa başı yoğunluğuna karşı hedefli gevşeme seansı.",
      durationMinutes: 45,
      price: 1300,
      staffIds: categoryStaffIds.masaj,
    },
    {
      id: "head-ritual",
      categoryId: "kafa-masaji",
      name: "Hint Kafa Masajı",
      description: "Kısa sürede rahatlama hissi oluşturan özel baş-boyun ritüeli.",
      durationMinutes: 30,
      price: 850,
      featured: true,
      staffIds: categoryStaffIds["kafa-masaji"],
    },
    {
      id: "head-spa",
      categoryId: "kafa-masaji",
      name: "Head Spa Mini Seans",
      description: "Saç derisini rahatlatan kısa ama etkili bakım akışı.",
      durationMinutes: 45,
      price: 1100,
      staffIds: categoryStaffIds["kafa-masaji"],
    },
    {
      id: "hair-scan",
      categoryId: "sac-taramasi",
      name: "Dermatoskopik Saç Analizi",
      description: "Saç derisi ve dökülme görünümünü değerlendiren detaylı tarama.",
      durationMinutes: 30,
      price: 700,
      featured: true,
      staffIds: categoryStaffIds["sac-taramasi"],
    },
    {
      id: "hair-plan",
      categoryId: "sac-taramasi",
      name: "Saç Güçlendirme Yol Haritası",
      description: "Taramaya göre bakım önerisi ve takip planı oluşturma.",
      durationMinutes: 45,
      price: 1250,
      staffIds: categoryStaffIds["sac-taramasi"],
    },
  ],
  packages: [
    {
      id: "bride-soft-glow",
      name: "Soft Glow Saç Paketi",
      description: "Kesim, ışıltı bakımı ve styling ile davet günleri için kusursuz hazırlık.",
      primaryServiceId: "signature-cut",
      includedServiceIds: ["signature-cut", "gloss-refresh"],
      durationMinutes: 135,
      price: 2450,
      savingsLabel: "350 TL avantaj",
      staffIds: categoryStaffIds.kuafor,
    },
    {
      id: "foot-comfort-ritual",
      name: "İpeksi Adımlar Paketi",
      description: "Spa pedikür ve topuk yenileme adımlarıyla tam ayak bakım deneyimi.",
      primaryServiceId: "spa-pedicure",
      includedServiceIds: ["spa-pedicure", "heel-renewal"],
      durationMinutes: 105,
      price: 1750,
      savingsLabel: "400 TL avantaj",
      staffIds: categoryStaffIds["ayak-bakimi"],
    },
    {
      id: "nail-elegance-edit",
      name: "Elegant Nails Paketi",
      description: "Kalıcı oje görünümünü güçlendirici bakım ile birleştiren zarif set.",
      primaryServiceId: "manicure-gel",
      includedServiceIds: ["manicure-gel", "nail-strength"],
      durationMinutes: 120,
      price: 1850,
      savingsLabel: "500 TL avantaj",
      staffIds: categoryStaffIds["tirnak-bakimi"],
    },
    {
      id: "skin-luster-session",
      name: "Cilt Işıltı Seremonisi",
      description: "Hydra Glow ve kolajen destekli bakımın tek blokta sunulduğu premium paket.",
      primaryServiceId: "hydra-glow",
      includedServiceIds: ["hydra-glow", "collagen-reset"],
      durationMinutes: 135,
      price: 2850,
      savingsLabel: "800 TL avantaj",
      staffIds: categoryStaffIds["cilt-bakimi"],
    },
    {
      id: "body-reset-ritual",
      name: "Body Reset Ritüeli",
      description: "G5 seansını rahatlatıcı masaj hissiyle birleştiren toparlayıcı akış.",
      primaryServiceId: "g5-tightening",
      includedServiceIds: ["g5-tightening", "back-neck-release"],
      durationMinutes: 90,
      price: 2150,
      savingsLabel: "250 TL avantaj",
      staffIds: categoryStaffIds.g5,
    },
    {
      id: "scalp-wellness-route",
      name: "Saç Derisi Wellness Paketi",
      description: "Saç analizi ve head spa ile desteklenen başlangıç bakım yolu.",
      primaryServiceId: "hair-scan",
      includedServiceIds: ["hair-scan", "head-spa"],
      durationMinutes: 75,
      price: 1550,
      savingsLabel: "250 TL avantaj",
      staffIds: categoryStaffIds["sac-taramasi"],
    },
  ],
  testimonials: [
    {
      id: "testimonial-1",
      author: "Aybüke K.",
      treatment: "Hydra Glow Cilt Bakımı",
      quote: "Salonun sakinliği ve bakımın sonucu birlikte çok güçlü. Cildim daha aydınlık göründü.",
    },
    {
      id: "testimonial-2",
      author: "Eda T.",
      treatment: "Elegant Nails Paketi",
      quote: "Detaylara çok dikkat edildi. Uzun süredir bu kadar temiz bir tırnak hizmeti almamıştım.",
    },
    {
      id: "testimonial-3",
      author: "Sinem B.",
      treatment: "Body Reset Ritüeli",
      quote: "Hem G5 hem rahatlama etkisini aynı gün hissetmek çok iyi geldi. Planlı ve güven veren bir ekip.",
    },
  ],
  campaigns: [
    {
      id: "campaign-1",
      kicker: "Nisan seçkisi",
      title: "Hafta içi gündüz saatlerine özel yumuşak fiyat aralığı",
      body: "12:00-16:00 arasındaki seçili bakım randevularında paket odaklı avantajlı demo akışı gösterilir.",
    },
    {
      id: "campaign-2",
      kicker: "Yeni danışan",
      title: "İlk analiz randevusuna sonrası için kişiselleştirilmiş bakım önerisi",
      body: "Saç taraması ve cilt bakımından sonra panel tarafında öneri kartı gösterimi yapılır.",
    },
  ],
};

export function getSeedAppointmentsDateOffsets() {
  const tomorrow = getNextOpenDate(new Date());
  const nextDayDate = new Date(`${tomorrow}T12:00:00`);
  nextDayDate.setDate(nextDayDate.getDate() + 1);
  return {
    tomorrow,
    dayAfter: new Intl.DateTimeFormat("en-CA").format(nextDayDate),
  };
}
